- hosts: MTL-F5-DR
  collections:
    - f5networks.f5_bigip
  connection: httpapi
  
  tasks:
    - name: Collect BIG-IP information
      bigip_device_info:
        gather_subset:
          - interfaces
          - vlans
