- hosts: MTL-F5-DR
  collections:
    - f5networks.f5_bigip
  connection: httpapi
  
  tasks:
   - name: Run show version on remote devices
     bigip_command:
     commands: show sys version
     register: result
     debug:
       msg: "{{ result }}"
      
